--liquibase formatted sql
--changeset mykidevs:1
CREATE TABLE IF NOT EXISTS verification_tokens(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value VARCHAR(255) NOT NULL,
    user_id BIGINT,
    exp_date TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_verify_token_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
--rollback DROP TABLE verification_tokens