spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      url: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
server:
  port: 8080